# Test with latest node version
image: node:latest

# Cache dependencies
cache:
  paths:
    - node_modules/

# Run unit tests
test:
  only:
    refs:
      - master
  before_script:
    # Install
    - npm install
  script:
    # Run Jest in CI mode
    - npm test -- --ci

# Publish package
publish:
  stage: deploy
  only:
    refs:
      - master
  before_script:
    # Build library
    - npm run build
    # Configure auth token access
    - echo '${NPM_TOKEN}' && echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
  script:
    # Publish to NPM
    - npm publish --access public
