# Test with latest node version
image: node:latest

# Cache dependencies
cache:
  paths:
    - node_modules/
    - "$HOME/.npm"
  
variables:
  NPM_TOKEN: "$NPM_TOKEN"

# Run unit tests
test:
  only:
    refs:
      - master
  script:
    # Install
    - npm ci
    # Run Jest in CI mode
    - npm test -- --ci

# Publish package
publish:
  stage: deploy
  only:
    refs:
      - master
  script:
    # Publish to NPM
    - npm publish --access public
